### ISSUE TITLE
Highlight browser versions behind a flag

### ISSUE THREAD

**Issue by matuzo** [5t3ph/eleventy-plugin-css-browser-support#2]
Here's how the browser support table looks like on my website. It shows a browser version for each browser, but `:has()` is only supported behind a flag in Firefox.

<img width="832" alt="Screenshot 2022-09-28 at 20 23 55" src="https://user-images.githubusercontent.com/1496761/192859877-566176d7-5b5d-4d9d-b699-0fb51a8f73bc.png">

It'd be great if we could add a class to flagged browsers so that we can differentiate between full and flagged support.

For example:
<img width="866" alt="Screenshot 2022-09-28 at 20 27 47" src="https://user-images.githubusercontent.com/1496761/192860419-3ce26c45-b702-42a5-b481-a7c3965a593d.png">

I was thinking about something like this:

```js
  let tableCellClasses;
  
  if (flagged) {
    tableCellClasses = `${PLUGIN}-cell--flagged`;
  }
  
  if (support === "N/A") {
    tableCellClasses = `${PLUGIN}-cell--na`;
  }
  
  tableRow += `<td ${
    tableCellClasses ? `class="${tableCellClasses}"` : ``
  }>${support}</td>`;
  });
```

I'll create a PR if that sounds okay.

**Comment by 5t3ph** [comment]
@matuzo added in v0.3.0, thanks for the suggestion!
