### ISSUE TITLE
Add optional caption option

### ISSUE THREAD

**Issue by matuzo** [5t3ph/eleventy-plugin-css-browser-support#3]
I'd love to be able to add a `<caption>` to tables. Do you think this would be useful to others, too?

I was thinking about something like this:

```
eleventyConfig.addPlugin(cssBrowserSupport, {
  tableCaption: "Browser Suppport"
});
```

This would result in:

```html
<table class="css-support-table">
  <caption>Browser Suppport</caption>
  <thead></thead>
  <tbody></tbody>
</table>
```

Omitting the option results in no caption.

```
eleventyConfig.addPlugin(cssBrowserSupport);
```

```html
<table class="css-support-table">
  <thead></thead>
  <tbody></tbody>
</table>
```

**Comment by 5t3ph** [comment]
@matuzo added in v0.3.0 as both a plugin option as well as an optional override per table by adding a second string after the properties list 🙌 

Thanks again!
